const HTTP_OK = 200;
const HTTP_CREATED = 201;
const HTTP_NO_CONTENT = 204;
const HTTP_INTERNAL_SERVER_ERROR = 500;
const HTTP_BAD_REQUEST = 400;

module.exports = {
  HTTP_CREATED,
  HTTP_NO_CONTENT,
  HTTP_OK,
  HTTP_INTERNAL_SERVER_ERROR,
  HTTP_BAD_REQUEST,
};
